version: "3.9"

services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: mqtt-ngrok
    command: start --all --config /etc/ngrok.yml
    ports:
      - "4040:4040"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    depends_on:
      - mqtt
    restart: unless-stopped
